### ISSUE TITLE
hexo g 时报了个错

### ISSUE THREAD

**Issue by liyanwei0418** [elmorec/hexo-theme-inside#1]
ReferenceError: hexo is not defined
    at module.exports (/home/hexo/themes/inside/scripts/lib/generator/api/config.js:8:18)
    at Hexo.module.exports (/home/hexo/themes/inside/scripts/lib/generator/api/index.js:10:8)
    at Hexo.tryCatcher (/home/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/hexo/node_modules/hexo/lib/hexo/index.js:340:24
    at tryCatcher (/home/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/hexo/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/hexo/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by xuxusheng** [comment]
我也遇到了这个问题，很漂亮的主题，作者加油

**Comment by xujiaji** [comment]
This theme is great! But I also encountered this problem. Some people say because of the hexo version of the change

```
hexo: 3.4.3
hexo-cli: 1.0.4
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

**Comment by elmorec** [comment]
Updated, thanks for your support.

**Comment by elmorec** [comment]
@liyanwei0418 close this issue, thx.
