### ISSUE TITLE
How to modify the avatar? How to add article homepage picture?

### ISSUE THREAD

**Issue by xujiaji** [elmorec/hexo-theme-inside#2]

**Comment by elmorec** [comment]
@xujiaji 设置主题文件夹里的`_config.yaml`
```yaml
profile:
  email: example@mail.com
```
头像是基于这个邮箱地址的，参见[gravatar](https://en.gravatar.com/)。

列表的图片是在post的头信息里加`thumbnail`属性，如：
```markdown
---
title: You've got to find what you love
date: 2015-03-20 22:37:03
author: who knows
tags:
 - people
thumbnail: http://ov0ydb6iw.bkt.clouddn.com/images/people/jobs.jpg_s0
---
```

本是自用的主题，尚有很多不完善，见谅，也多谢支持！

**Comment by xujiaji** [comment]
@elmorec 多谢分享！你做的这个主题太棒了！头像可以了，但是我在文章头信息里添加`thumbnail`后出现了问题。
```
---
title: Hello World
thumbnail: http://ov0ydb6iw.bkt.clouddn.com/images/people/jobs.jpg_s0
---
```

```
E:\blog.xujiaji.com>hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: exports.qiniu is not a function
    at exports.pick (E:\blog.xujiaji.com\themes\inside\scripts\lib\utils.js:51:52)
    at locals.posts.sort.filter.map.post (E:\blog.xujiaji.com\themes\inside\scripts\lib\generator\api\post.js:7:88)
    at Query.map (E:\blog.xujiaji.com\node_modules\warehouse\lib\query.js:229:17)
    at Hexo.module.exports (E:\blog.xujiaji.com\themes\inside\scripts\lib\generator\api\post.js:7:76)
    at Hexo.module.exports (E:\blog.xujiaji.com\themes\inside\scripts\lib\generator\api\index.js:12:13)
    at Hexo.tryCatcher (E:\blog.xujiaji.com\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog.xujiaji.com\node_modules\bluebird\js\release\method.js:15:34)
    at E:\blog.xujiaji.com\node_modules\hexo\lib\hexo\index.js:340:24
    at tryCatcher (E:\blog.xujiaji.com\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\blog.xujiaji.com\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\blog.xujiaji.com\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (E:\blog.xujiaji.com\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (E:\blog.xujiaji.com\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\blog.xujiaji.com\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\blog.xujiaji.com\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\blog.xujiaji.com\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by elmorec** [comment]
@xujiaji 去掉了自用的第三方图片cdn的图片路径补全，如果没有问题了，issue关掉吧。

**Comment by xujiaji** [comment]
@elmorec 可以了

**Comment by JoeyTribbianiJr** [comment]
图片不能用本地的吗

**Comment by xujiaji** [comment]
@JoeyTribbianiJr 可以在hexo根目录的source目录下创建一个放图片的文件夹，目录和路径如下图
![_005](https://user-images.githubusercontent.com/16447251/34029144-e02f50ba-e1a1-11e7-9f72-eab833b902a1.png)

**Comment by JoeyTribbianiJr** [comment]
感谢热情回答。那我打开post-asset-folder了，目前还不支持放在文章文件夹里对吧？

**Comment by xujiaji** [comment]
你可以试试看！我也是感觉这样能行，然后就这样做了，结果它还真能行！>_<|||

**Comment by JoeyTribbianiJr** [comment]
哈哈，稍等我去给你买个橘子。

**Comment by JoeyTribbianiJr** [comment]
哈哈，稍等我去给你买个橘子。
所以我看有的主题首页有categories，有的没有，原来主题开发这一块是只需要修改渲染的样式，不需要动深层次的route解析之类的代码吗？
ps:好像不行

**Comment by xujiaji** [comment]
= =

**Comment by elmorec** [comment]
总觉得主题有点简陋，any ideal or suggestions？

**Comment by xujiaji** [comment]
可以在加一个tag栏吗？如果想看分类的文章不方便，需要从文章底部Tag标签进入相应tag列表。例如像这种：http://haojen.github.io/tags/

**Comment by JoeyTribbianiJr** [comment]
要求categories。
另外换个背景图片就华丽多了，我认为并不简陋

**Comment by xujiaji** [comment]
另外如果用手机浏览器浏览会出现很多奇怪的问题

**Comment by elmorec** [comment]
@xujiaji bug吗

**Comment by xujiaji** [comment]
是的！以下列出几个
1、切换Home和Archives会出现下面这种Home和Archives都有的情况。
![screenshot_2017-12-16-13-16-50-169_com android br](https://user-images.githubusercontent.com/16447251/34067591-ffed79b8-e264-11e7-937f-801077cdd1ff.png)
2、有时候右下角按钮无法点击
3、左侧列表底部会重叠
![qq_pic_merged_1513402340302](https://user-images.githubusercontent.com/16447251/34067615-a4726f0c-e265-11e7-92b0-f2a995ef287b.jpg)
4、如图
![screenshot_2017-12-16-13-34-17-565_com android br](https://user-images.githubusercontent.com/16447251/34067621-ed4e2d92-e265-11e7-9ff8-124a3ea19e93.png)

**Comment by xujiaji** [comment]
这是我的博客地址：http://blog.xujiaji.com/

**Comment by elmorec** [comment]
测栏底部重叠我知道，后面改成滚动，其他的好像都是兼容问题，因为我手机上也用的chrome所以没发现，我看一下...

**Comment by xujiaji** [comment]
我在手机chrome上试了下，在这里确实都没问题

**Comment by elmorec** [comment]
@xujiaji 兼容问题已经修复

**Comment by xujiaji** [comment]
@elmorec Good！我试了下，没问题。

**Comment by xujiaji** [comment]
目前markdown的排版上，在手机，下面两种情况会导致跨越边界的情况。

|1、放链接的时候|2、表格|
|:-:|:-:|
|http://blog.xujiaji.com/post/android-bug-list|http://blog.xujiaji.com/post/happy-bubble|
|![screenshot_2017-12-17-13-55-33-328_com android ch](https://user-images.githubusercontent.com/16447251/34077038-249b5072-e333-11e7-8cb3-4bf180ac3958.png)|![screenshot_2017-12-17-13-59-40-861_com android br](https://user-images.githubusercontent.com/16447251/34077040-29ac4c06-e333-11e7-816a-4c1ea62cfc64.png)|

**Comment by elmorec** [comment]
这个比较坑……
一部分语言的国际化用的angular官方的国际化机制（看[这里](https://angular.io/guide/i18n)），最终会生成特定语言的几个脚本文件，`hexo generate` 的时候，需要根据语言取对应的脚本文件，这一块现在实现的方式有点随性 >.<，`hexo serve` 命令和 `hexo generate` 命令有点不一样，取对应的脚本的代码没有执行，我后面想办法优化下。

你想要的效果可以通过下面方式实现
把 `inside/source/_main.82ed0e88e6feddfe3347.zh-Hans.js` 复制一份，重命名为 `inside/source/main.82ed0e88e6feddfe3347.js`

**Comment by xujiaji** [comment]
原来如此啊！*٩(๑´∀`๑)ง*好的
