### ISSUE TITLE
代码块使用``` ```时，样式可能会出现错误

### ISSUE THREAD

**Issue by Jooecy** [elmorec/hexo-theme-inside#27]
当文章中代码使用```包裹时，例如：

\```

这里时代码块

\```

代码单行长度过长时，在手机端浏览时，代码块并不会以“横拉框”的形式显示，导致页面宽度变的和代码长度一样宽。不能自适应。

而在使用{% codeblock lang:python %}   {% endcodeblock %}包裹代码就不会出现该问题。

请问是不是主题配置或hexo配置的原因？

**Comment by elmorec** [comment]
有链接吗

**Comment by Jooecy** [comment]
应该是我没有清楚缓存导致的，已经解决了问题。

**Comment by Jooecy** [comment]
但是更新到你最新的主题，出错了。

**Comment by elmorec** [comment]
这里有说明 [v1.9.0](https://github.com/elmorec/hexo-theme-inside/releases/tag/v1.9.0)，如果还出错，贴一下错误，多谢支持。

**Comment by Jooecy** [comment]
更新后，没对HEOX/_config.yml文件做处理，hexo g 后报以下错误，之后我把HEOX/_config.yml中的index_generator.per_page注释掉，依然报错。错误如下。


`TypeError: Cannot read property '0' of null
    at Hexo.urlForHelper (/home/joecy/Blog/node_modules/hexo/lib/plugins/helper/url_for.js:7:11)
    at Hexo.module.exports (/home/joecy/Blog/themes/inside/lib/generator/config.js:25:61)
    at Hexo.tryCatcher (/home/joecy/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/joecy/Blog/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/home/joecy/Blog/node_modules/hexo/lib/hexo/index.js:336:26)
    at tryCatcher (/home/joecy/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/joecy/Blog/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/joecy/Blog/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/home/joecy/Blog/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/home/joecy/Blog/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/home/joecy/Blog/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/joecy/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/joecy/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
`

以下时我现在的环境：
`hexo: 3.7.1
hexo-cli: 1.1.0
os: Linux 4.15.0-21deepin-generic linux x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
`

**Comment by Jooecy** [comment]
对不起老哥，我知道错误在哪里了。`HEOX/_config.yml`中root不可以设置为`/`，要设置为一级域名的样子，例如abc.com，就可以了。不知道为什么。

**Comment by elmorec** [comment]
好像问题不是这里，你改了就好了吗

**Comment by Jooecy** [comment]
不对，问题好像不在这里，好像是清理缓存可以解决报错。具体我也不知道。你复现了吗？

**Comment by elmorec** [comment]
你有配置 feed 吗

**Comment by Jooecy** [comment]
没有，只要在执行hexo g、hexo s 命令前先执行hexo clean，就不会报错。否则就报错。你试试。

**Comment by Jooecy** [comment]
可以复现吗？需要我帮忙做测试吗？

**Comment by elmorec** [comment]
已修复，试试看。

**Comment by Jooecy** [comment]
好的，辛苦了！

**Comment by Jooecy** [comment]
没问题了，这次新版主要做了什么变化？

**Comment by elmorec** [comment]
主要是文件生成逻辑的优化，UI 无变化。

**Comment by elmorec** [comment]
知道原因了...

**Comment by Jooecy** [comment]
再次辛苦了！

**Comment by elmorec** [comment]
我太马虎，你 pull 一下看看。

**Comment by Jooecy** [comment]
OK了，谢谢
