### ISSUE TITLE
配置文件的menu使用的问题

### ISSUE THREAD

**Issue by Seven-stars** [elmorec/hexo-theme-inside#46]
_config.yml 文件里面（主题内的）

```
menu:
  主页: /
   #About: /about
   #Links: /links
```
这一段，将#删掉就会出错QAQ

**Comment by Seven-stars** [comment]
求助 @elmorec

~~我竟然还给您发了封英文邮件QAQ~~

**Comment by elmorec** [comment]
报什么错？

**Comment by Seven-stars** [comment]
@elmorec
有点长QAQ
```
$ hexo g
ERROR Plugin load failed: hexo-theme-inside
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: bad indentation of a mapping entry at line 17, column 9:
       About: /about
            ^
    at generateError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockMapping (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
    at composeNode (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (D:\hexo\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\hexo\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'toLowerCase' of undefined
    at gravatarHelper (D:\hexo\node_modules\hexo\lib\plugins\helper\gravatar.js:15:58)
    at Hexo.<anonymous> (D:\hexo\themes\hexo-theme-inside-master\lib\config.js:17:18)
    at emitNone (events.js:106:13)
    at Hexo.emit (events.js:208:7)
    at Hexo._generate (D:\hexo\node_modules\hexo\lib\hexo\index.js:315:8)
    at loadDatabase.then.then (D:\hexo\node_modules\hexo\lib\hexo\index.js:259:22)
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise._fulfill (D:\hexo\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (D:\hexo\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (D:\hexo\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)

```

**Comment by elmorec** [comment]
`bad indentation of a mapping entry at line 17`
缩进不对啊，两个空格的缩进，你检查下是不是。

**Comment by Seven-stars** [comment]
@elmorec  真的好了呢QAQ

谢谢φ(>ω<*)
