### ISSUE TITLE
hexo g 报错

### ISSUE THREAD

**Issue by EnnisWu** [elmorec/hexo-theme-inside#64]
ERROR Plugin load failed: hexo-theme-inside
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'substring' of undefined
    at exports.getPagePath (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\themes\hexo-theme-inside\lib\utils.js:67:44)
    at config.routes.locals.pages.map.page (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\themes\hexo-theme-inside\lib\generator\config.js:23:46)
    at Model._Query.Query.Query.map (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\warehouse\lib\query.js:229:17)
    at Hexo.module.exports (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\themes\hexo-theme-inside\lib\generator\config.js:23:34)
    at Hexo.tryCatcher (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.map.key (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\hexo\lib\hexo\index.js:336:26)
    at tryCatcher (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\map.js:30:10)
    at _drainQueueStep (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (C:\Users\Ennis-PC\EnnisWu\EnnisWu-projects\Hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by elmorec** [comment]
`npm uninstall hexo-theme-inside`

 请把主题放到项目根目录的 themes 文件夹，如 themes/inside

**Comment by EnnisWu** [comment]
> `npm uninstall hexo-theme-inside`
> 
> 请把主题放到项目根目录的 themes 文件夹，如 themes/inside

我是放在themes里的

**Comment by elmorec** [comment]
首先确保 node_modules 里没有 hexo-theme-inside~

**Comment by elmorec** [comment]
有个一样的问题~ #49

**Comment by EnnisWu** [comment]
node_modules 和 package.json 里没有 hexo-theme-inside，我是直接下载下来放在 themes 里的

**Comment by EnnisWu** [comment]
我好像找到原因了，如果在 source 里放了 js 、css 文件，hexo g 就会报错，如果 md 里写了 js ，hexo g 不会报错但是 hexo s 回报错
