### ISSUE TITLE
Plugin load failed: hexo-theme-inside

### ISSUE THREAD

**Issue by omnibingo** [elmorec/hexo-theme-inside#66]
报错如下

ERROR Plugin load failed: hexo-theme-inside
Error: EISDIR: illegal operation on a directory, read
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'substring' of undefined
    at exports.getPagePath (/Users/bingo/Dropbox/Talk2it_D/talk2.it/themes/inside/lib/utils.js:67:44)
    at config.routes.locals.pages.map.page (/Users/bingo/Dropbox/Talk2it_D/talk2.it/themes/inside/lib/generator/config.js:23:46)
    at Model._Query.Query.Query.map (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/warehouse/lib/query.js:229:17)
    at Hexo.module.exports (/Users/bingo/Dropbox/Talk2it_D/talk2.it/themes/inside/lib/generator/config.js:23:34)
    at Hexo.tryCatcher (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.map.key (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/hexo/lib/hexo/index.js:344:26)
    at tryCatcher (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/bingo/Dropbox/Talk2it_D/talk2.it/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)

**Comment by elmorec** [comment]
主题不是插件，请确保：
1. /node_modules 下没有 hexo-theme-inside
2. /package.json 的 dependencies 里没有 hexo-theme-inside

如果了解不多，建议不要通过 `npm install`，直接下载 zip。
